# Generated by Django 5.1.2 on 2024-12-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_profile_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kvk',
            field=models.CharField(default='Geen KVK', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='pc',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
