# Generated by Django 5.1.2 on 2025-01-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='unit_price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(),
        ),
    ]
